-- AI Usage Logs - Phase 2: Firebase Integration
-- Auto-generated by Drizzle Kit with manual RLS policies

CREATE TYPE "public"."ai_provider" AS ENUM('hermes', 'firebase_ai');--> statement-breakpoint
CREATE TABLE "ai_usage_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"provider" "ai_provider" NOT NULL,
	"model" text NOT NULL,
	"input_tokens" integer,
	"output_tokens" integer,
	"cost_usd" numeric(10, 6),
	"latency_ms" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ai_usage_logs" ADD CONSTRAINT "ai_usage_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

-- Enable RLS on ai_usage_logs
ALTER TABLE "ai_usage_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

-- RLS Policy: Users can view their own usage logs
CREATE POLICY "users_view_own_logs" ON "ai_usage_logs"
  AS PERMISSIVE FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);--> statement-breakpoint

-- RLS Policy: Service role can insert usage logs (for Edge Functions)
CREATE POLICY "service_role_insert_logs" ON "ai_usage_logs"
  AS PERMISSIVE FOR INSERT
  TO service_role
  WITH CHECK (true);--> statement-breakpoint

-- Create index for efficient user queries
CREATE INDEX "idx_ai_usage_logs_user_id" ON "ai_usage_logs" ("user_id");--> statement-breakpoint

-- Create index for time-based queries (analytics)
CREATE INDEX "idx_ai_usage_logs_created_at" ON "ai_usage_logs" ("created_at" DESC);--> statement-breakpoint

-- Create composite index for user + time queries
CREATE INDEX "idx_ai_usage_logs_user_time" ON "ai_usage_logs" ("user_id", "created_at" DESC);