-- AI Performance Metrics - Phase 4: Analytics & A/B Testing
-- Auto-generated by Drizzle Kit with manual RLS policies and indexes

CREATE TABLE "ai_performance_metrics" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"provider" "ai_provider" NOT NULL,
	"model" text NOT NULL,
	"latency_ms" integer NOT NULL,
	"input_tokens" integer NOT NULL,
	"output_tokens" integer NOT NULL,
	"used_tools" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ai_performance_metrics" ADD CONSTRAINT "ai_performance_metrics_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

-- Enable RLS on ai_performance_metrics
ALTER TABLE "ai_performance_metrics" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

-- RLS Policy: Users can view their own metrics
CREATE POLICY "users_view_own_metrics" ON "ai_performance_metrics"
  AS PERMISSIVE FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);--> statement-breakpoint

-- RLS Policy: Service role can insert metrics (for Edge Functions and Analytics Service)
CREATE POLICY "service_role_insert_metrics" ON "ai_performance_metrics"
  AS PERMISSIVE FOR INSERT
  TO service_role
  WITH CHECK (true);--> statement-breakpoint

-- Create index for efficient provider comparison queries
CREATE INDEX "idx_ai_performance_metrics_provider" ON "ai_performance_metrics" ("provider");--> statement-breakpoint

-- Create index for time-based queries (analytics dashboards)
CREATE INDEX "idx_ai_performance_metrics_created_at" ON "ai_performance_metrics" ("created_at" DESC);--> statement-breakpoint

-- Create composite index for provider + time queries (A/B testing analytics)
CREATE INDEX "idx_ai_performance_metrics_provider_time" ON "ai_performance_metrics" ("provider", "created_at" DESC);