import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/models.dart';
import '../providers/supabase_provider.dart';

part 'ai_usage_repository.g.dart';

/// Repository for AI usage tracking and analytics
/// Provides type-safe access to the ai_usage_logs table
@riverpod
AiUsageRepository aiUsageRepository(Ref ref) {
  final client = ref.watch(supabaseClientProvider);
  return AiUsageRepository(client);
}

class AiUsageRepository {
  final SupabaseClient _client;

  AiUsageRepository(this._client);

  /// Log an AI API call for cost tracking and analytics
  Future<void> logUsage({
    required String userId,
    required AiProvider provider,
    required String model,
    int? inputTokens,
    int? outputTokens,
    double? costUsd,
    int? latencyMs,
  }) async {
    final log = AiUsageLogs(
      id: '', // Will be generated by database
      userId: userId,
      provider: provider,
      model: model,
      inputTokens: inputTokens,
      outputTokens: outputTokens,
      costUsd: costUsd,
      latencyMs: latencyMs,
      createdAt: DateTime.now(), // Will be set by database default
    );

    await _client.from('ai_usage_logs').insert(log.toJson());
  }

  /// Get all usage logs for a specific user
  Future<List<AiUsageLogs>> getUserLogs(String userId) async {
    final response = await _client
        .from('ai_usage_logs')
        .select()
        .eq('user_id', userId)
        .order('created_at', ascending: false);

    return (response as List)
        .map((json) => AiUsageLogs.fromJson(json as Map<String, dynamic>))
        .toList();
  }

  /// Get usage logs for a specific user and provider
  Future<List<AiUsageLogs>> getUserLogsByProvider(
    String userId,
    AiProvider provider,
  ) async {
    final response = await _client
        .from('ai_usage_logs')
        .select()
        .eq('user_id', userId)
        .eq('provider', provider.value)
        .order('created_at', ascending: false);

    return (response as List)
        .map((json) => AiUsageLogs.fromJson(json as Map<String, dynamic>))
        .toList();
  }

  /// Get total usage statistics for a user
  Future<UsageStats> getUserStats(String userId) async {
    final logs = await getUserLogs(userId);

    int totalCalls = logs.length;
    int totalInputTokens = 0;
    int totalOutputTokens = 0;
    double totalCost = 0.0;
    int hermesUsage = 0;
    int firebaseAiUsage = 0;

    for (final log in logs) {
      totalInputTokens += log.inputTokens ?? 0;
      totalOutputTokens += log.outputTokens ?? 0;
      totalCost += log.costUsd ?? 0.0;

      if (log.provider == AiProvider.hermes) {
        hermesUsage++;
      } else if (log.provider == AiProvider.firebaseAi) {
        firebaseAiUsage++;
      }
    }

    return UsageStats(
      totalCalls: totalCalls,
      totalInputTokens: totalInputTokens,
      totalOutputTokens: totalOutputTokens,
      totalCost: totalCost,
      hermesUsage: hermesUsage,
      firebaseAiUsage: firebaseAiUsage,
    );
  }

  /// Get usage logs within a date range
  Future<List<AiUsageLogs>> getLogsByDateRange(
    String userId,
    DateTime startDate,
    DateTime endDate,
  ) async {
    final response = await _client
        .from('ai_usage_logs')
        .select()
        .eq('user_id', userId)
        .gte('created_at', startDate.toIso8601String())
        .lte('created_at', endDate.toIso8601String())
        .order('created_at', ascending: false);

    return (response as List)
        .map((json) => AiUsageLogs.fromJson(json as Map<String, dynamic>))
        .toList();
  }
}
