import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/models.dart';
import '../providers/supabase_provider.dart';

part 'subscription_repository.g.dart';

/// Repository for subscription management
/// Provides type-safe access to the subscriptions table
@riverpod
SubscriptionRepository subscriptionRepository(Ref ref) {
  final client = ref.watch(supabaseClientProvider);
  return SubscriptionRepository(client);
}

class SubscriptionRepository {
  final SupabaseClient _client;

  SubscriptionRepository(this._client);

  /// Get a user's current subscription
  Future<Subscriptions?> getUserSubscription(String userId) async {
    final response = await _client
        .from('subscriptions')
        .select()
        .eq('user_id', userId)
        .order('created_at', ascending: false)
        .limit(1)
        .maybeSingle();

    if (response == null) return null;
    return Subscriptions.fromJson(response as Map<String, dynamic>);
  }

  /// Get all subscriptions for a user (including historical)
  Future<List<Subscriptions>> getUserSubscriptionHistory(String userId) async {
    final response = await _client
        .from('subscriptions')
        .select()
        .eq('user_id', userId)
        .order('created_at', ascending: false);

    return (response as List)
        .map((json) => Subscriptions.fromJson(json as Map<String, dynamic>))
        .toList();
  }

  /// Create a new subscription
  Future<Subscriptions> createSubscription({
    required String userId,
    required String planId,
    required SubscriptionStatus status,
    String? stripeSubscriptionId,
    String? stripeCustomerId,
    DateTime? expiresAt,
  }) async {
    final subscription = Subscriptions(
      id: '', // Will be generated by database
      userId: userId,
      status: status,
      planId: planId,
      stripeSubscriptionId: stripeSubscriptionId,
      stripeCustomerId: stripeCustomerId,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      expiresAt: expiresAt,
    );

    final response = await _client
        .from('subscriptions')
        .insert(subscription.toJson())
        .select()
        .single();

    return Subscriptions.fromJson(response as Map<String, dynamic>);
  }

  /// Update subscription status
  Future<void> updateSubscriptionStatus(
    String subscriptionId,
    SubscriptionStatus newStatus,
  ) async {
    await _client
        .from('subscriptions')
        .update({
          'status': newStatus.value,
          'updated_at': DateTime.now().toIso8601String(),
        })
        .eq('id', subscriptionId);
  }

  /// Cancel a subscription
  Future<void> cancelSubscription(String subscriptionId) async {
    await updateSubscriptionStatus(
      subscriptionId,
      SubscriptionStatus.cancelled,
    );
  }

  /// Check if a user has an active subscription
  Future<bool> hasActiveSubscription(String userId) async {
    final subscription = await getUserSubscription(userId);
    if (subscription == null) return false;

    return subscription.status == SubscriptionStatus.active ||
        subscription.status == SubscriptionStatus.trialing;
  }

  /// Update Stripe-related fields
  Future<void> updateStripeInfo(
    String subscriptionId, {
    String? stripeSubscriptionId,
    String? stripeCustomerId,
  }) async {
    final updates = <String, dynamic>{
      'updated_at': DateTime.now().toIso8601String(),
    };

    if (stripeSubscriptionId != null) {
      updates['stripe_subscription_id'] = stripeSubscriptionId;
    }
    if (stripeCustomerId != null) {
      updates['stripe_customer_id'] = stripeCustomerId;
    }

    await _client
        .from('subscriptions')
        .update(updates)
        .eq('id', subscriptionId);
  }

  /// Set subscription expiration date
  Future<void> setExpirationDate(
    String subscriptionId,
    DateTime expiresAt,
  ) async {
    await _client
        .from('subscriptions')
        .update({
          'expires_at': expiresAt.toIso8601String(),
          'updated_at': DateTime.now().toIso8601String(),
        })
        .eq('id', subscriptionId);
  }

  /// Get all active subscriptions (admin function)
  Future<List<Subscriptions>> getAllActiveSubscriptions() async {
    final response = await _client
        .from('subscriptions')
        .select()
        .eq('status', SubscriptionStatus.active.value)
        .order('created_at', ascending: false);

    return (response as List)
        .map((json) => Subscriptions.fromJson(json as Map<String, dynamic>))
        .toList();
  }
}
